import type { Course, Lesson, Quiz, Transaction, CoinPackage, Certificate, MascotInfo } from '@/types';

// Mascot definitions
export const mascots: Record<string, MascotInfo> = {
  novice: {
    level: 'novice',
    name: 'Byte',
    description: 'Just starting your coding journey. Keep learning!',
    minCoins: 0,
    maxCoins: 499,
  },
  practitioner: {
    level: 'practitioner',
    name: 'Logic',
    description: 'Building solid programming foundations. Great progress!',
    minCoins: 500,
    maxCoins: 1499,
  },
  expert: {
    level: 'expert',
    name: 'Syntax',
    description: 'Master coder and mentor. You inspire others!',
    minCoins: 1500,
    maxCoins: Infinity,
  },
};

// Mock courses
export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Python Fundamentals',
    description: 'Master the basics of Python programming with hands-on projects.',
    thumbnail: '/placeholder.svg',
    instructor: 'Dr. Sarah Chen',
    duration: '8 hours',
    lessonsCount: 24,
    price: 0,
    isLocked: false,
    isEnrolled: true,
    progress: 75,
    category: 'Programming',
    level: 'beginner',
  },
  {
    id: 'course-2',
    title: 'JavaScript Essentials',
    description: 'Build interactive web applications with modern JavaScript.',
    thumbnail: '/placeholder.svg',
    instructor: 'Mike Rodriguez',
    duration: '10 hours',
    lessonsCount: 32,
    price: 0,
    isLocked: false,
    isEnrolled: true,
    progress: 45,
    category: 'Web Development',
    level: 'beginner',
  },
  {
    id: 'course-3',
    title: 'React Development',
    description: 'Create powerful user interfaces with React and modern tooling.',
    thumbnail: '/placeholder.svg',
    instructor: 'Emma Wilson',
    duration: '12 hours',
    lessonsCount: 28,
    price: 200,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Web Development',
    level: 'intermediate',
  },
  {
    id: 'course-4',
    title: 'Data Structures & Algorithms',
    description: 'Essential computer science concepts for technical interviews.',
    thumbnail: '/placeholder.svg',
    instructor: 'Prof. David Kim',
    duration: '15 hours',
    lessonsCount: 40,
    price: 350,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Computer Science',
    level: 'intermediate',
  },
  {
    id: 'course-5',
    title: 'Node.js Backend Development',
    description: 'Build scalable server-side applications with Node.js.',
    thumbnail: '/placeholder.svg',
    instructor: 'Alex Thompson',
    duration: '11 hours',
    lessonsCount: 26,
    price: 250,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Backend',
    level: 'intermediate',
  },
  {
    id: 'course-6',
    title: 'SQL & Database Design',
    description: 'Master relational databases and write efficient queries.',
    thumbnail: '/placeholder.svg',
    instructor: 'Maria Santos',
    duration: '9 hours',
    lessonsCount: 22,
    price: 150,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Database',
    level: 'beginner',
  },
  {
    id: 'course-7',
    title: 'TypeScript Mastery',
    description: 'Add type safety to your JavaScript projects with TypeScript.',
    thumbnail: '/placeholder.svg',
    instructor: 'Chris Anderson',
    duration: '7 hours',
    lessonsCount: 20,
    price: 180,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Programming',
    level: 'intermediate',
  },
  {
    id: 'course-8',
    title: 'Git & GitHub Workflow',
    description: 'Version control essentials for professional developers.',
    thumbnail: '/placeholder.svg',
    instructor: 'Jordan Lee',
    duration: '5 hours',
    lessonsCount: 15,
    price: 0,
    isLocked: false,
    isEnrolled: false,
    progress: 0,
    category: 'Tools',
    level: 'beginner',
  },
  {
    id: 'course-9',
    title: 'Docker & Containerization',
    description: 'Deploy applications anywhere with Docker containers.',
    thumbnail: '/placeholder.svg',
    instructor: 'Nina Patel',
    duration: '8 hours',
    lessonsCount: 18,
    price: 300,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'DevOps',
    level: 'advanced',
  },
  {
    id: 'course-10',
    title: 'API Design & REST',
    description: 'Design clean, scalable APIs that developers love.',
    thumbnail: '/placeholder.svg',
    instructor: 'Tom Bradley',
    duration: '6 hours',
    lessonsCount: 16,
    price: 200,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Backend',
    level: 'intermediate',
  },
  {
    id: 'course-11',
    title: 'CSS & Modern Layouts',
    description: 'Create stunning responsive designs with modern CSS.',
    thumbnail: '/placeholder.svg',
    instructor: 'Lisa Chen',
    duration: '7 hours',
    lessonsCount: 21,
    price: 0,
    isLocked: false,
    isEnrolled: false,
    progress: 0,
    category: 'Web Development',
    level: 'beginner',
  },
  {
    id: 'course-12',
    title: 'Testing & TDD',
    description: 'Write reliable code with test-driven development.',
    thumbnail: '/placeholder.svg',
    instructor: 'James Wright',
    duration: '8 hours',
    lessonsCount: 19,
    price: 220,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Quality',
    level: 'intermediate',
  },
  {
    id: 'course-13',
    title: 'AWS Cloud Fundamentals',
    description: 'Deploy and scale applications on Amazon Web Services.',
    thumbnail: '/placeholder.svg',
    instructor: 'Rachel Green',
    duration: '14 hours',
    lessonsCount: 35,
    price: 400,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Cloud',
    level: 'advanced',
  },
  {
    id: 'course-14',
    title: 'GraphQL API Development',
    description: 'Build flexible APIs with GraphQL and Apollo.',
    thumbnail: '/placeholder.svg',
    instructor: 'Kevin Park',
    duration: '9 hours',
    lessonsCount: 23,
    price: 280,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Backend',
    level: 'advanced',
  },
  {
    id: 'course-15',
    title: 'Security for Developers',
    description: 'Protect your applications from common vulnerabilities.',
    thumbnail: '/placeholder.svg',
    instructor: 'Diana Ross',
    duration: '10 hours',
    lessonsCount: 25,
    price: 350,
    isLocked: true,
    isEnrolled: false,
    progress: 0,
    category: 'Security',
    level: 'advanced',
  },
];

// Mock lessons for course-1
export const mockLessons: Lesson[] = [
  {
    id: 'lesson-1',
    courseId: 'course-1',
    title: 'Introduction to Python',
    description: 'Get started with Python programming language.',
    videoUrl: 'https://example.com/video1',
    duration: '12:30',
    order: 1,
    isCompleted: true,
    quizId: 'quiz-1',
  },
  {
    id: 'lesson-2',
    courseId: 'course-1',
    title: 'Variables and Data Types',
    description: 'Understanding Python data types and variables.',
    videoUrl: 'https://example.com/video2',
    duration: '18:45',
    order: 2,
    isCompleted: true,
    quizId: 'quiz-2',
  },
  {
    id: 'lesson-3',
    courseId: 'course-1',
    title: 'Control Flow',
    description: 'If statements, loops, and program control.',
    videoUrl: 'https://example.com/video3',
    duration: '22:15',
    order: 3,
    isCompleted: false,
    quizId: 'quiz-3',
  },
  {
    id: 'lesson-4',
    courseId: 'course-1',
    title: 'Functions',
    description: 'Creating reusable code with functions.',
    videoUrl: 'https://example.com/video4',
    duration: '25:00',
    order: 4,
    isCompleted: false,
  },
];

// Mock quiz
export const mockQuiz: Quiz = {
  id: 'quiz-1',
  lessonId: 'lesson-1',
  title: 'Python Basics Quiz',
  passingScore: 70,
  coinReward: 25,
  questions: [
    {
      id: 'q1',
      question: 'What is Python primarily known for?',
      options: [
        'Complex syntax',
        'Readability and simplicity',
        'Only for web development',
        'Compiled language only',
      ],
      correctAnswer: 1,
    },
    {
      id: 'q2',
      question: 'How do you print "Hello World" in Python?',
      options: [
        'console.log("Hello World")',
        'System.out.println("Hello World")',
        'print("Hello World")',
        'echo "Hello World"',
      ],
      correctAnswer: 2,
    },
    {
      id: 'q3',
      question: 'Which of these is a valid Python variable name?',
      options: ['2myvar', 'my-var', 'my_var', 'my var'],
      correctAnswer: 2,
    },
    {
      id: 'q4',
      question: 'What symbol is used for comments in Python?',
      options: ['//', '/*', '#', '--'],
      correctAnswer: 2,
    },
  ],
};

// Mock transactions
export const mockTransactions: Transaction[] = [
  {
    id: 'tx-1',
    userId: 'user-1',
    type: 'earned',
    amount: 25,
    description: 'Completed "Introduction to Python" quiz',
    createdAt: '2024-01-20T14:30:00Z',
    reference: 'quiz-1',
  },
  {
    id: 'tx-2',
    userId: 'user-1',
    type: 'earned',
    amount: 50,
    description: 'Completed lesson milestone',
    createdAt: '2024-01-19T10:15:00Z',
    reference: 'lesson-5',
  },
  {
    id: 'tx-3',
    userId: 'user-1',
    type: 'spent',
    amount: -150,
    description: 'Unlocked "SQL & Database Design"',
    createdAt: '2024-01-18T16:45:00Z',
    reference: 'course-6',
  },
  {
    id: 'tx-4',
    userId: 'user-1',
    type: 'purchased',
    amount: 500,
    description: 'Purchased coin package',
    createdAt: '2024-01-15T09:00:00Z',
    reference: 'package-2',
  },
  {
    id: 'tx-5',
    userId: 'user-1',
    type: 'earned',
    amount: 100,
    description: 'Welcome bonus',
    createdAt: '2024-01-15T08:00:00Z',
  },
];

// Coin packages for purchase
export const coinPackages: CoinPackage[] = [
  {
    id: 'package-1',
    coins: 100,
    price: 4.99,
    bonus: 0,
  },
  {
    id: 'package-2',
    coins: 500,
    price: 19.99,
    bonus: 50,
    popular: true,
  },
  {
    id: 'package-3',
    coins: 1000,
    price: 34.99,
    bonus: 150,
  },
  {
    id: 'package-4',
    coins: 2500,
    price: 79.99,
    bonus: 500,
  },
];

// Mock certificates
export const mockCertificates: Certificate[] = [
  {
    id: 'cert-1',
    userId: 'user-1',
    courseId: 'course-8',
    courseName: 'Git & GitHub Workflow',
    issuedAt: '2024-01-10',
    certificateUrl: '/certificates/cert-1.pdf',
  },
];

// Categories for filtering
export const courseCategories = [
  'All',
  'Programming',
  'Web Development',
  'Backend',
  'Database',
  'DevOps',
  'Cloud',
  'Security',
  'Tools',
  'Computer Science',
  'Quality',
];

// Admin stats
export const adminStats = {
  totalUsers: 1247,
  totalCourses: 15,
  totalRevenue: 24580,
  activeStudents: 892,
  completedCourses: 3420,
  certificatesIssued: 567,
};
